name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: yarn install

    - name: Linting
      run: yarn lint
      continue-on-error: false

    - name: Testing
      run: yarn test
      continue-on-error: false

    - name: Building
      run: yarn build
      continue-on-error: false
